language: node_js

node_js: stable

notifications:
  pushover:
    api_key: ${PUSHOVER_APIKEY}
    users: 
      - ${PUSHOVER_USER}

cache:
  apt: true
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'
  - chmod +x ./publish.sh
  - echo ${PUSHOVER_USER}
  - echo haha
  - echo ${PUSHOVER_APIKEY}

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  #- ./publish.sh
  - cd ./public
  - git init
  - git config user.name "roccowang"
  - git config user.email "roccowang95@outlook.com"
  - git add .
  - git commit -m "TravisCI built"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - raw

env:
  global:
    - GH_REF: github.com/roccowang/roccowang.github.io.git
