language: node_js
node_js: stable
notifications:
cache:
  apt: true
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'
- export VERSION=1.$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
- echo TRAVIS_BUILD_WEB_URL:${TRAVIS_BUILD_WEB_URL}
- echo TRAVIS_JOB_WEB_URL:${TRAVIS_JOB_WEB_URL}
install:
- npm install
script:
- hexo clean
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "roccowang"
- git config user.email "roccowang95@outlook.com"
- echo "# Rocco\'s Blog" > README.md
- echo '[![Build Status](https://travis-ci.org/roccowang/roccowang.github.io.svg?branch=raw)](https://travis-ci.org/roccowang/roccowang.github.io)' >> README.md
- git add .
- git commit -m "TravisCI built. ${VERSION}"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
after_success:
- curl -XPOST https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage -d '{"chat_id":'${TG_CHAT_ID}', "text":"'"Blog build done. ${TRAVIS_JOB_WEB_URL}"'"}' -H "content-type: application/json"
after_failure:
- curl -XPOST https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage -d '{"chat_id":'${TG_CHAT_ID}', "text":"'"Blog built with error. ${TRAVIS_JOB_WEB_URL}"'"}' -H "content-type: application/json"
branches:
  only:
  - raw
env:
  global:
  - GH_REF: github.com/roccowang/roccowang.github.io.git
